GridLayout:
    cols: 1
    Label:
        id: moeda1
        text: "1º texto"
    Label:
        id: moeda2
        text: "2º texto"
    Label:
        id: moeda3
        text: "3º texto"
    Label:
        id: moeda4
        text: "4º texto"
    Label:
        id: moeda5
        text: "5º texto"
    Label:
        id: moeda6
        text: "6º texto"
    Label:
        id: moeda7
        text: "7º texto"